on:
  push:
    branches:
      - master
  pull_request:
name: downstream-dependencies
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
        repo:
          - java-bigquery
          - java-bigqueryconnection
          - java-spanner
          - java-storage
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}
      - run: java -version
      - run: .kokoro/client-library-check.sh ${{matrix.repo}}
