on:
  push:
    branches:
    - 0.20.x
  pull_request:
name: downstream
jobs:
  dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
        repo:
        - java-bigquery
        - java-bigqueryconnection
        - java-spanner
        - java-storage
        - java-pubsub
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
